name: Node.js CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - run: npm --version
    - run: node --version
      uses: actions/checkout@v3
      with:
        node-version: 16.x
    - run: npm install
    - run: npm start